- id: alpha
    <<: *base_dim
    description: "Universo espejo de alta energía"
    quantum_flux: 1.7
    entropy_level: 0.42
    temporal_rules:
      causality: flexible
      paradox_resolution: quarantine
    features:
      - quantum_entanglement
      - temporal_folding
    resources:
      cpu: "12q"
      memory: "64qb"
      storage: "2pb"
