# Dimensiones primarias
dimensions:
  - id: prime
    <<: *base_dim
    description: "Realidad principal de referencia"
    quantum_link: true
    temporal_rules:
      causality: strict
      paradox_resolution: auto_correct
    resources:
      cpu: "8q"
      memory: "32qb"
      storage: "1pb"
