| Par치metro               | Valor Base  | Rango Operativo |
|-------------------------|-------------|-----------------|
| Teletransportes/sec     | 1,200       | 500-5,000       |
| Compresi칩n M치xima       | 10:1        | 5:1 a 20:1      |
| Tolerancia a Fallos     | 99.98%      | 99.9-99.999%    |
| Qubits por Conexi칩n     | 12          | 8-24            |
