# config/security/access_rules.yaml
acces}⁰
  Prime:
    access: "Completo"
    permissions: ["ALL"]
  Alpha:
    access: "Científico"
    permissions: ["READ", "EXECUTE", "ANALYZE"]
  Beta:
    access: "Restringido"
    permissions: ["READ"]
  default:
    access: "Denegado"
