name: "Cosmic Automation Pipeline"

on:
  # Activadores Multi-Dimensionales
  push:
    branches: [ "andromeda", "milky-way" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '0 0 * * *'  # Construcción diaria del continuum
  workflow_dispatch:
    inputs:
      quantum_energy:
        description: 'Nivel de energía para ejecución'
        required: true
        default: '7'
        type: choice
        options: [ '5', '7', '9', '11' ]
