  # =================================
  # FASE 3: SINCRONIZACIÓN INTERDIMENSIONAL
  # =================================
  reality_sync:
    name: "Sincronización de Realidades"
    needs: deploy_shards
    runs-on: nebula-sync-node
    timeout-minutes: 30

    steps:
      - name: "Iniciar Sincronizador Cuántico"
        uses: mechmind-actions/reality-sync@v2
        with:
          primary-cluster: ${{ needs.quantum_cluster_init.outputs.cluster_id }}
          sync-mode: full-spectrum
          temporal-tolerance: 0.7

      - name: "Verificar Coherencia Dimensional"
        run: |
          python nebula/coherence_check.py \
            --cluster ${{ needs.quantum_cluster_init.outputs.cluster_id }} \
            --threshold 0.95 \
            --full-report

      - name: "Estabilizar Puntos de Entrelazamiento"
        if: always()
        uses: mechmind-actions/quantum-stabilize@v1
        with:
          cluster-id: ${{ needs.quantum_cluster_init.outputs.cluster_id }}
          stabilization-mode: aggressive

      - name: "Notificar al Monitor Central"
        uses: mechmind-actions/nebula-alert@v3
        with:
          status: ${{ job.status }}
          cluster: ${{ needs.quantum_cluster_init.outputs.cluster_id }}
          shards: ${{ needs.quantum_cluster_init.outputs.reality_shards }}
